from collections import Counter
a='Hello welcome to Cathay 60th year anniversary'
b=a.upper()
arr1=(list(b))
count_arr1 = Counter(arr1)
print("E", count_arr1["E"])
print("A", count_arr1["A"])
print("H", count_arr1["H"])
print("L", count_arr1["L"])
print("O", count_arr1["O"])
print("T", count_arr1["T"])
print("Y", count_arr1["Y"])
print("R", count_arr1["R"])
print("C", count_arr1["C"])
print("N", count_arr1["N"])
print("W", count_arr1["W"])
print("M", count_arr1["M"])
print("6", count_arr1["6"])
print("0", count_arr1["0"])
print("I", count_arr1["I"])
print("V", count_arr1["V"])
print("S", count_arr1["S"])